### ISSUE TITLE
[Rewrite Status] Testing Checklist

### ISSUE THREAD

**Issue by osiset** [osiset/laravel-shopify#415]
Given the number of emails I am receiving asking about the current status of the new version. I am making a sticky issue surrounding it so people can be more aware of what's going on.

As preface, if you're unaware, I am unable to attend to the current publish version due to time. All my efforts have been directed on this new rewrite which has gone well and will most likely (if no major issues pop up), be released end of week.

[X] = Done, tested
[ ] = Untested yet

**Code**
- [X] Unit testing, full coverage on important parts
- [X] Functional testing, on important parts

**Physical Testing**
- [X] Installation process
- [X] Installation with billing plan
- [X] Installation with freemium enabled
- [X] Installation with billing plan but shop is grandfathered
- [X] Installation with billing plan, decline, should re-ask for billing
- [X] Installation with billing plan, delete app day later, re-ask for billing and trial days should change
- [X] Two tabs open of app in two different shops, each shop should not see other shop details (reauth)
- [X] Webhooks install
- [X] Script tags install
- [X] After authenticate job fires
- [X] Chrome cookie works
- [X] Base Blade views work
- [X] Proxy app works
- [X] Webhook controller functioning, maps to proper job
- [X] Middleware (Shopify, Proxy, Webhook) functioning normally
- [X] Shops controlled by Laravel Users functioning normally

_Last Updated: March 16th, 2020_

**Comment by osiset** [comment]
Given status of the above testing on physical stores, I am prepping release now...
Docs will require updating before releasing.
